In [1]:
import numpy as np 
import pandas as pd
import math
from google.colab import drive
import csv
import matplotlib.pyplot as plt

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/drug200.csv')
df.head(10)

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  drugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  drugY
9   43   M     LOW      NORMAL   19.368  drugY

In [4]:
print(df.shape)

(200, 6)


In [5]:
df['Sex']= df['Sex'].map({'F':1,'M':0})
df['BP']=df['BP'].map({'HIGH':2,'NORMAL':1,'LOW':0})
df['Cholesterol']=df['Cholesterol'].map({'HIGH':2,'NORMAL':1,'LOW':0})
df['Drug'] = df['Drug'].map({'drugA':5,'drugB':4,'drugC':3,'drugX':2,'drugY':1})

In [6]:
df

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    1   2            2   25.355     1
1     47    0   0            2   13.093     3
2     47    0   0            2   10.114     3
3     28    1   1            2    7.798     2
4     61    1   0            2   18.043     1
..   ...  ...  ..          ...      ...   ...
195   56    1   0            2   11.567     3
196   16    0   0            2   12.006     3
197   52    0   1            2    9.894     2
198   23    0   1            1   14.020     2
199   40    1   0            1   11.349     2

[200 rows x 6 columns]

In [7]:
df.corr()

Age       Sex        BP  Cholesterol   Na_to_K      Drug
Age          1.000000 -0.102027 -0.120918     0.068234 -0.063119  0.004828
Sex         -0.102027  1.000000  0.044952    -0.008811  0.125008 -0.098573
BP          -0.120918  0.044952  1.000000    -0.032208  0.036871  0.328665
Cholesterol  0.068234 -0.008811 -0.032208     1.000000 -0.010000  0.055629
Na_to_K     -0.063119  0.125008  0.036871    -0.010000  1.000000 -0.589120
Drug         0.004828 -0.098573  0.328665     0.055629 -0.589120  1.000000

In [8]:
X = df[['Age','Sex','BP','Cholesterol','Na_to_K']]
y = df['Drug']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train,y_train)
y_pred = neigh.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[12  2  0  0  1]
 [ 0 10  0  0  1]
 [ 1  2  2  0  0]
 [ 0  0  0  3  0]
 [ 0  1  0  1  4]]
              precision    recall  f1-score   support

           1       0.92      0.80      0.86        15
           2       0.67      0.91      0.77        11
           3       1.00      0.40      0.57         5
           4       0.75      1.00      0.86         3
           5       0.67      0.67      0.67         6

    accuracy                           0.78        40
   macro avg       0.80      0.76      0.74        40
weighted avg       0.81      0.78      0.77        40



In [14]:
data = (13,0,0,2,6.2)
data_as_numpy_array = np.asarray(data)
data_reshape = data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(data_reshape)
print(std_data)
ketqua = neigh.predict(std_data)
if (ketqua==1):
  print('DÙng thuốc Y')
else:
  if(ketqua==2):
    print('DÙng thuốc X')
  if(ketqua==3):
    print('Dùng thuốc C')
  if(ketqua==4):
    print('dùng thuốc B')
  if(ketqua==5):
    print('Dùng thuốc A')


[[-2.01777631 -0.96317747 -1.33378103  0.90453403 -1.38205356]]
DÙng thuốc X


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
